repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: local
    hooks:
      - id: lint-fast
        name: lint-fast
        entry: npm run lint:fast
        language: system
        pass_filenames: false
      - id: lint
        name: lint
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: format-check
        name: format-check
        entry: npm run format:check
        language: system
        pass_filenames: false
